[saturn]
email = ""
password = ""
categories = []
category_regex = ""
ignore_sleep = false
# Beware that >10 can cause issues with Discord's 200 characters limit!
cookies = 10
start_url = ""
# You can set a webhook for all the types or a dedicated one for each type
webhook_url = ""
webhook_role_ping = ""
stock_webhook_role_ping = ""
cookie_webhook_role_ping = ""
admin_webhook_role_ping = ""
# Important!
# If you use multiple proxies the them as http://user:pass@foo.bar:8080
# Set only proxy_urls or proxy_url NOT both
proxy_urls = []
proxy_url = ""
proxy_username = ""
proxy_password = ""
dynamo_db_region = ""
dynamo_db_table_name = ""
dynamo_db_access_key = ""
dynamo_db_secret_access_key = ""
# The hashes from the queries. Tend to change often
loginSHA256 = ""
categorySHA256 = ""
wishlistSHA256 = ""
addProductSHA256 = ""
getProductSHA256 = ""

[mmde]
email = ""
password = ""
categories = []
category_regex = ""
ignore_sleep = false
# Beware that >10 can cause issues with Discord's 200 characters limit!
cookies = 10
start_url = ""
# You can set a webhook for all the types or a dedicated one for each type
webhook_url = ""
webhook_role_ping = ""
stock_webhook_role_ping = ""
cookie_webhook_role_ping = ""
admin_webhook_role_ping = ""
# Important!
# If you use multiple proxies the them as http://user:pass@foo.bar:8080
# Set only proxy_urls or proxy_url NOT both
proxy_urls = []
proxy_url = ""
proxy_username = ""
proxy_password = ""
dynamo_db_region = ""
dynamo_db_table_name = ""
dynamo_db_access_key = ""
dynamo_db_secret_access_key = ""
# The hashes from the queries. Tend to change often
loginSHA256 = ""
categorySHA256 = ""
wishlistSHA256 = ""
addProductSHA256 = ""
getProductSHA256 = ""

[mmat]
email = ""
password = ""
categories = []
category_regex = ""
ignore_sleep = false
# Beware that >10 can cause issues with Discord's 200 characters limit!
cookies = 10
start_url = ""
# You can set a webhook for all the types or a dedicated one for each type
webhook_url = ""
webhook_role_ping = ""
stock_webhook_role_ping = ""
cookie_webhook_role_ping = ""
admin_webhook_role_ping = ""
# Important!
# If you use multiple proxies the them as http://user:pass@foo.bar:8080
# Set only proxy_urls or proxy_url NOT both
proxy_urls = []
proxy_url = ""
proxy_username = ""
proxy_password = ""
dynamo_db_region = ""
dynamo_db_table_name = ""
dynamo_db_access_key = ""
dynamo_db_secret_access_key = ""
# The hashes from the queries. Tend to change often
loginSHA256 = ""
categorySHA256 = ""
wishlistSHA256 = ""
addProductSHA256 = ""
getProductSHA256 = ""
