[saturn]
email = ""
password = ""
categories = []
category_regex = ""
ignore_sleep = false
# You can set a webhook for all the types or a dedicated one for each type
webhook_url = ""
webhook_role_ping = ""
stock_webhook_role_ping = ""
cookie_webhook_role_ping = ""
admin_webhook_role_ping = ""
proxy_url = ""
proxy_username = ""
proxy_password = ""
start_url = ""

[mmde]
email = ""
password = ""
categories = []
category_regex = ""
ignore_sleep = false
# You can set a webhook for all the types or a dedicated one for each type
webhook_url = ""
webhook_role_ping = ""
stock_webhook_role_ping = ""
cookie_webhook_role_ping = ""
admin_webhook_role_ping = ""
proxy_url = ""
proxy_username = ""
proxy_password = ""
start_url = ""

[mmat]
email = ""
password = ""
categories = []
category_regex = ""
ignore_sleep = false
# You can set a webhook for all the types or a dedicated one for each type
webhook_url = ""
webhook_role_ping = ""
stock_webhook_role_ping = ""
cookie_webhook_role_ping = ""
admin_webhook_role_ping = ""
proxy_url = ""
proxy_username = ""
proxy_password = ""
start_url = ""
