[saturn]
email = ""
password = ""
webhook_url = ""
webhook_role_ping = ""
proxy_url = ""
proxy_username = ""
proxy_password = ""

[mmde]
email = ""
password = ""
webhook_url = ""
webhook_role_ping = ""
proxy_url = ""
proxy_username = ""
proxy_password = ""

[mmat]
email = ""
password = ""
webhook_url = ""
webhook_role_ping = ""
proxy_url = ""
proxy_username = ""
proxy_password = ""
